# Generated by Django 4.2.7 on 2024-12-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insert_api_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='brand',
            field=models.CharField(default='Default Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='harvest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
