# Generated by Django 4.2.7 on 2024-12-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insert_api_code', '0002_harvest_brand_harvest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
