# Generated by Django 4.2.7 on 2024-12-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insert_api_code', '0003_alter_harvest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
