# Generated by Django 4.2.7 on 2024-12-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insert_api_code', '0004_harvest_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='product_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
