# Generated by Django 4.2.7 on 2025-01-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Harvest_application', '0002_alter_login_id_alter_login_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=5000, null=True)),
                ('retailer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Master_data',
            },
        ),
    ]
